# ControlPlaneBaseRole
#
# Used by: -aws-control-plane-base pipeline
# manages platform cluster aws-managed aspects

module "ControlPlaneBaseRole" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-role"
  version = "6.3.0"
  create  = true

  name            = "ControlPlaneBaseRole"
  path            = "/Roles/"
  use_name_prefix = false

  trust_policy_permissions = {
    TrustRoleAndServiceToAssume = {
      actions = [
        "sts:TagSession",
        "sts:AssumeRole",
      ]
      principals = [{
        type = "AWS"
        identifiers = [
          "arn:aws:iam::${var.aws_account_id}:root",
        ]
      }]
    }
  }

  policies = {
    custom = aws_iam_policy.ControlPlaneBaseRolePolicy.arn,
    state  = aws_iam_policy.S3StateBucketPolicy.arn
  }
}

# role permissions
resource "aws_iam_policy" "ControlPlaneBaseRolePolicy" {
  name = "ControlPlaneBaseRolePolicy"
  path = "/Policies/"

  policy = jsonencode({
    "Version" : "2012-10-17"
    "Statement" : [
      {
        "Action" : [
          "route53:AssociateVPCWithHostedZone",
          "route53:ChangeResourceRecordSets",
          "route53:ChangeTagsForResource",
          "route53:GetChange",
          "route53:CreateHealthCheck",
          "route53:CreateHostedZone",
          "route53:CreateKeySigningKey",
          "route53:CreateVPCAssociationAuthorization",
          "route53:DeactivateKeySigningKey",
          "route53:DeleteHealthCheck",
          "route53:DeleteHostedZone",
          "route53:DeleteKeySigningKey",
          "route53:DeleteVPCAssociationAuthorization",
          "route53:DisassociateVPCFromHostedZone",
          "route53:GetHostedZone",
          "route53:GetHostedZoneCount",
          "route53:GetHostedZoneLimit",
          "route53:ListHostedZones",
          "route53:ListHostedZonesByName",
          "route53:ListHostedZonesByVPC",
          "route53:ListResourceRecordSets",
          "route53:ListTagsForResource",
          "route53:ListTagsForResources",
          "route53:ListVPCAssociationAuthorizations",
          "route53:UpdateHostedZoneComment",
          "autoscaling:AttachInstances",
          "autoscaling:CreateAutoScalingGroup",
          "autoscaling:CreateLaunchConfiguration",
          "autoscaling:CreateOrUpdateTags",
          "autoscaling:DeleteAutoScalingGroup",
          "autoscaling:DeleteLaunchConfiguration",
          "autoscaling:DeleteTags",
          "autoscaling:Describe*",
          "autoscaling:DetachInstances",
          "autoscaling:SetDesiredCapacity",
          "autoscaling:UpdateAutoScalingGroup",
          "autoscaling:SuspendProcesses",
          "ec2:*Console*",
          "ec2:Describe*",
          "ec2:*NetworkAclEntry",
          "ec2:*SecurityGroup*",
          "ec2:*KeyPair",
          "ec2:*LaunchTemplate*",
          "ec2:*NetworkInterface*",
          "ec2:*Image*",
          "ec2:*Placement*",
          "ec2:*Snapshot*",
          "ec2:*Tags",
          "ec2:*Volume*",
          "ec2:*InstanceProfile*",
          "ec2:AssignPrivateIpAddresses",
          "ec2:AssociateRouteTable",
          "ec2:CancelConversionTask",
          "ec2:CancelImportTask",
          "ec2:ConfirmProductInstance",
          "ec2:Import*",
          "ec2:ModifyInstance*",
          "ec2:MonitorInstances",
          "ec2:RebootInstances",
          "ec2:ReportInstanceStatus",
          "ec2:ResetInstanceAttribute",
          "ec2:RunInstances",
          "ec2:StartInstances",
          "ec2:StopInstances",
          "ec2:TerminateInstances",
          "ec2:UnassignPrivateIpAddresses",
          "ec2:UnmonitorInstances",
          "ec2-instance-connect:SendSerial*",
          "ec2:ModifyTrafficMirror*",
          "ec2:DeleteTrafficMirror*",
          "elasticloadbalancing:DescribeLoadBalancers",
          "elasticloadbalancing:DescribeTags",
          "elasticloadbalancing:DescribeLoadBalancerAttributes",
          "elasticfilesystem:*Backup*",
          "elasticfilesystem:*FileSystem*",
          "elasticfilesystem:*Mount*",
          "elasticfilesystem:*Tag*",
          "elasticfilesystem:*Untag*",
          "elasticfilesystem:Describe*",
          "elasticfilesystem:*LifecycleConfiguration",
          "ec2:CreateNetworkInterface",
          "ec2:DescribeNetworkInterfaces",
          "ec2:DescribeSubnets",
          "eks:*",
          "iam:AddClientIDToOpenIDConnectProvider",
          "iam:AddRoleToInstanceProfile",
          "iam:AttachRolePolicy",
          "iam:CreateInstanceProfile",
          "iam:CreateOpenIDConnectProvider",
          "iam:CreateServiceLinkedRole",
          "iam:CreatePolicy",
          "iam:CreatePolicyVersion",
          "iam:CreateRole",
          "iam:*Addon",
          "iam:DeleteInstanceProfile",
          "iam:DeleteOpenIDConnectProvider",
          "iam:DeletePolicy",
          "iam:DeletePolicyVersion",
          "iam:DeleteRole",
          "iam:DeleteRolePolicy",
          "iam:DeleteServiceLinkedRole",
          "iam:DetachRolePolicy",
          "iam:GetInstanceProfile",
          "iam:GetOpenIDConnectProvider",
          "iam:GetPolicy",
          "iam:GetPolicyVersion",
          "iam:GetRole",
          "iam:GetRolePolicy",
          "iam:List*",
          "iam:PassRole",
          "iam:PutRolePolicy",
          "iam:Remove*",
          "iam:Tag*",
          "iam:Untag*",
          "iam:Update*",
          "logs:CreateLogGroup",
          "logs:DescribeLogGroups",
          "logs:DeleteLogGroup",
          "logs:List*",
          "logs:PutRetentionPolicy",
          "logs:TagLogGroup",
          "logs:UntagLogGroup",
          "kms:CreateGrant",
          "kms:CreateKey",
          "kms:DeleteKey",
          "kms:DescribeKey",
          "kms:GetKeyPolicy",
          "kms:GetKeyRotationStatus",
          "kms:ListResourceTags",
          "kms:ScheduleKeyDeletion",
          "kms:EnableKeyRotation",
          "kms:TagResource",
          "kms:CreateAlias",
          "kms:DeleteAlias",
          "kms:ListAliases",
          "ssm:GetParameter",
          "ecr:createRepository",
          "ecr:deleteRepository",
          "ecr:describeRepositories",
          "ecr:getAuthorizationToken",
          "ecr:ListTagsForResource",
          "ecr:GetLifecyclePolicy",
          "ecr:PutLifecyclePolicy",
          "ecr:DeleteLifecyclePolicy",
          "ecr:GetRepositoryPolicy",
          "ecr:SetRepositoryPolicy",
          "ecr:DeleteRepositoryPolicy",
          "ecr:TagResource",
          "ecr:UntagResource",
          "logs:TagResource",
          "logs:UntagResource",
          "sqs:*",
          "events:*",
          "cloudformation:*",
          "acm-pca:CreateCertificateAuthority",
          "acm-pca:DeleteCertificateAuthority",
          "acm-pca:DescribeCertificateAuthority",
          "acm-pca:GetCertificateAuthorityCertificate",
          "acm-pca:GetCertificateAuthorityCsr",
          "acm-pca:GetCertificateAuthorityPolicy",
          "acm-pca:ListCertificateAuthorities",
          "acm-pca:ListTags",
          "acm-pca:TagCertificateAuthority",
          "acm-pca:UntagCertificateAuthority",
          "acm-pca:UpdateCertificateAuthority",
          "acm-pca:IssueCertificate",
          "acm-pca:GetCertificate",
          "acm-pca:ListPermissions",
          "acm-pca:ListTagsForCertificateAuthority",
          "acm-pca:PutCertificateAuthorityPolicy",
          "acm-pca:RemoveCertificateAuthorityPolicy",
          "acm-pca:ImportCertificateAuthorityCertificate",
          "acm-pca:ImportCertificateAuthorityCsr",
          "acm-pca:ImportCertificateAuthorityPolicy",
          "acm-pca:ImportCertificateAuthorityCertificate",
          "acm-pca:RenewCertificateAuthority",
          "acm-pca:RevokeCertificate",
          "acm-pca:TagCertificate",
          "acm-pca:UntagCertificate",
          "secretsmanager:GetSecretValue",
          "secretsmanager:CreateSecret",
          "secretsmanager:DeleteSecret",
          "secretsmanager:DescribeSecret",
          "secretsmanager:ListSecrets",
          "secretsmanager:TagResource",
          "secretsmanager:UntagResource",
          "ecr:PutImageScanningConfiguration",
          "ecr:DeleteImageScanningConfiguration",
          "ecr:GetImageScanningConfiguration",
          "ssm:PutParameter",
          "ssm:DeleteParameter",
          "ssm:DescribeParameters",
          "ssm:GetParameters",
          "ssm:ListTagsForResource",
          "ssm:AddTagsToResource",
          "ssm:RemoveTagsFromResource",
          "kms:Create*",
          "kms:Describe*",
          "kms:Enable*",
          "kms:List*",
          "kms:Put*",
          "kms:Update*",
          "kms:Revoke*",
          "kms:Disable*",
          "kms:Get*",
          "kms:Delete*",
          "kms:ScheduleKeyDeletion",
          "kms:CancelKeyDeletion",
          "kms:Encrypt",
          "kms:Decrypt",
          "kms:ReEncrypt*",
          "kms:GenerateDataKey*",
          "kms:DescribeKey"

        ]
        "Effect" : "Allow"
        "Resource" : "*"
      },
    ]
  })
}
